wx:
  config:
    appId: "wxbde01b6b360d94ba"
    appSecret: "de853e89620357a9e1b440cd54685929"
    templateId: "QVM8pNHdGSQ9vreKKtgTEGe0CSm8y46NiBXvRnMxTFg"
    openidList:
      - "oYCr65zFDpnwTRmUFpkmGE4WzSh4"
      - "oYCr65wwAU4jQcsK3SPhSbJTD8AQ"
    weatherAppId: "58275617"
    weatherAppSecret: "Z1aljHBS"
    city: "都匀"
    togetherDate: "2023-03-30"
    birthday1: "05-08"
    birthday2: "06-08"
    message: "Have a nice day and love you everyday,ZhouJing"
    enableDaily: false
    token: "a1kth55g81w7qf3tf65gf6tczwzvub8m"

server:
  port: 8081
